### ISSUE TITLE
posts being deleted 

### ISSUE THREAD

**Issue by andrewkim51** [Avnsx/fansly#14]
It seems like every time I scrape, when the user deletes their posts, it also deletes it from my folder. Why does this happen? Isn't the point of scraping to keep the files that are uploaded no matter if it gets deleted or not?

**Comment by Avnsx** [comment]
This is not possible; the program doesn't interact with any already downloaded images. You can create a new fansly account yourself and than post something, scrape it & delte the post and scrape again to verify this

**Comment by andrewkim51** [comment]
@Avnsx checked, and that's definitely what happened. If this could be fixed that would be great!

**Comment by Avnsx** [comment]
> @Avnsx checked, and that's definitely what happened. If this could be fixed that would be great!

Fixed in [version 0.3.2](https://github.com/Avnsx/fansly/releases/tag/v0.3.2)
