### ISSUE TITLE
No longer downloading new content

### ISSUE THREAD

**Issue by Nostang3** [Avnsx/fansly#17]
Version: Latest (Ran updater to check)
Model: indigowhite

Everything seems to work correctly but it won't download a post set made in the last 24hrs. It downloaded a set on the 21st just fine but the new set it's like it doesn't see it. Happy to do any testing needed.

**Comment by Avnsx** [comment]
Fixed with version 0.3.3

You can use the updater.exe, to comfortably update to the newest version @Nostang3

**Comment by Nostang3** [comment]
Just confirming the fix worked. I was able to download the troublesome set. Thanks.
