### ISSUE TITLE
i can't downlaod the content in private messages - Fansly

### ISSUE THREAD

**Issue by Milomamas** [Avnsx/fansly#2]
Hello Avnsx=) I Want Thank You For Your project about Fansly, is working well=)
But it seems to me that the program is not working for the content that is in the messages, i hope/wish you get a solution for this situation=)
Continuation of a good work

**Comment by OFfriend** [comment]
first get all groups `https://apiv2.fansly.com/api/v1/group`
than use the ID `/message?groupId=<id>&before=<0/before>&limit=50` to get all messages 👍

**Comment by Milomamas** [comment]
can you be more explicit because Authorization_Token is the same that i was use to donwload the media general and the User_Agent is the same too hmm=)

**Comment by Milomamas** [comment]
sorry, I don't understand, What is maintainer?
I have to change something in config.ini ?=)

**Comment by Milomamas** [comment]
![apiv2](https://user-images.githubusercontent.com/92674612/137640019-b31a907e-5065-4ff0-8aa9-7349fd682350.jpg)

**Comment by Avnsx** [comment]
> first get all groups `https://apiv2.fansly.com/api/v1/group` than use the ID `/message?groupId=<id>&before=<0/before>&limit=50` to get all messages 👍

Thanks for pointing this out. This repo was just recently released. If it continues to grow I'll be adding this in update v0.3, else you're of course free to contribute to it. I'm looking at all pull requests.

**Comment by Avnsx** [comment]
> can you be more explicit because Authorization_Token is the same that i was use to donwload the media general and the User_Agent is the same too hmm=)

I'm not sure what you're referring to here. There's no functionality to scrape messages yet, I'll be adding that in update v0.3 if the repo continues to grow. So spread the word 🤠 Apart from that here's the how to, incase you missed it. It does have some info about the ``UserAgent`` and ``Authorization_Token``, if that is what you meant: https://github.com/Avnsx/fansly#how-to

**Comment by Milomamas** [comment]
I Have Media " photos and videos" On DM "private messages" That creator sent to me and i cant download this photos and videos
when I use your code /program this content that I bought does not appear together with the photo/videos the creator has posted for her sub-creators=)

**Comment by Avnsx** [comment]
> not working for the content that is in the messages

messages scraping compatibility added in https://github.com/Avnsx/fansly/commit/db5f9878c7377a8d58f387753758653b37fc1ad8

currently only available in raw source, compiled version will come in a couple days
