### ISSUE TITLE
Every time the .exe is run, a new 160 MB folder is created in /AppData/Local/Temp

### ISSUE THREAD

**Issue by NightEC12** [Avnsx/fansly#24]
I'm not sure why exactly this is happening, but as the title states, every time I start a new run of "Fansly Scraper.exe" it creates a brand new folder inside of AppData/Local/Temp. Every one is filled with the same python files / libraries. It is incredibly annoying... I was wondering what was eating up my storage so much.
Otherwise, the program works.
I'm using version 0.3.3.0
![image](https://user-images.githubusercontent.com/89748710/172934196-b229ac99-1541-4d8e-90ce-daf091670ecf.png)

**Comment by Avnsx** [comment]
This is not happening from fansly scraper, but from selenium-wire which is integrated into Automatic Configurator. So unless you constantly start up the configurator this should not happen.

**Comment by Avnsx** [comment]
This can not happen anymore by the way, selenium-wire is now entirely removed.
