### ISSUE TITLE
Scraper Skipping Downloads

### ISSUE THREAD

**Issue by MattHasSoul** [Avnsx/fansly#25]
Thanks for the app!

The scraper seems to skip downloading some images if they're too similar to another image in the same post. For example, the model is standing in a doorway facing left; if there's another picture with the model not moving much (facing a different direction) then it only downloads one of the pictures.

Not a big deal, I was just trying to figure out why it had put less photos in the "Pictures" folder than was available on Fansly.

**Comment by Avnsx** [comment]
Well thanks for using it, also this bug is not fixable since the reason this happens in first place is because the decline duplicates algorithm is having a hard time chosing if the image is a duplicate or if it is just slightly different.
