### ISSUE TITLE
GIFS not downloading

### ISSUE THREAD

**Issue by Joakimgreenday** [Avnsx/fansly#26]
If there was a way to download gifs aswell that would be appreciated!

**Comment by Avnsx** [comment]
Well in theory, gifs should already download and get sorted into Videos. Not sure why they wouldn't? What creator are you encountering this bug with?

https://github.com/Avnsx/fansly/blob/57e90741b1b4a120b85791424bf0386ba5c4d14e/fansly_scraper.py#L231

**Comment by Avnsx** [comment]
Closed due to inactivity
