### ISSUE TITLE
Scraper Not Downloading Media From Messages

### ISSUE THREAD

**Issue by DennisKaizer** [Avnsx/fansly#27]
As title suggests, I am having trouble downloading media from messages. The scraper provides the line "No scrapable media found in messages" even though there is plenty of media to download from messages. Please help.

**Comment by DennisKaizer** [comment]
To add, I am using exectuable v0.3.3 manually as well because whenever I try to use the automatic configure, I get an error saying 
`Traceback (most recent call last):
  File "automatic_configurator.py", line 345, in <module>
NameError: name 'regex' is not defined`
The scraper does not work after this error so I have to resort to manual, so another issue I am having with this scraper.

**Comment by DennisKaizer** [comment]
To add, I am using exectuable v0.3.3 manually as well because whenever I try to use the automatic configure, I get an error saying 
`Traceback (most recent call last):
  File "automatic_configurator.py", line 345, in <module>
NameError: name 'regex' is not defined`
The scraper does not work after this error so I have to resort to manual, so another issue I am having with this scraper.

**Comment by Avnsx** [comment]
> As title suggests, I am having trouble downloading media from messages. The scraper provides the line "No scrapable media found in messages" even though there is plenty of media to download from messages. Please help.

Automatic configurator is not really doing a good job right now, partially it is patched and partially broken. I was already aware of its state and will eventually push an update for it.

Since automatic configurator has not worked for you and you still tried to use the scraper, you most likely messed up getting the authorization token / user agent, which results in the scraper not finding any content in messages (but if this is the case, you should not be able to download any stuff you paid for / have access to either from regular posts). Generally speaking though; scraping messages still works.

**Comment by DennisKaizer** [comment]
When I manually use the scraper, it still is getting the regular and paid photos and videos from the profile feed, but it does not getting media from the messages.

**Comment by Avnsx** [comment]
> When I manually use the scraper, it still is getting the regular and paid photos and videos from the profile feed, but it does not getting media from the messages.

What is your creators name?

**Comment by DennisKaizer** [comment]
simenssofia

**Comment by Avnsx** [comment]
Tried for both, the first one does not send unlocked media through messages so I can't verify if it works (but most likely yes) and the second one just worked, I could get the content without issues. It's definetly a problem on your side

**Comment by DennisKaizer** [comment]
No I'm still not able to see any downloaded messages. The only files I have downloaded are the posts from the profile.

Im using executable v0.3.3, downloaded all necessary python prompts and requirements.txt, manually inputted the config file, and am still having issues. Do you have any other ideas that could help?

**Comment by Avnsx** [comment]
> Do you have any other ideas that could help?

are you sure you installed ``selenium-wire==4.6.0`` and ``undetected_chromedriver==3.0.6`` with those specific versions?

**Comment by Avnsx** [comment]
> Yeah I have those installed. I've tried multiple creators and the scraper says "no scrapable media found in messages" for all of them. What python version do you have?

Works for any python version above 3.6+. I don't think I can help you with this issue to be honest.

**Comment by Avnsx** [comment]
Closed due to inactivity
