### ISSUE TITLE
Naming files by date posted feature?

### ISSUE THREAD

**Issue by pamman2** [Avnsx/fansly#28]
Hello! I'm just wondering if it's possible to have an option to add the post date to the file name? With all the ones I've downloaded so far, all of the files seem to be out of order according to the creator's video/image set.

**Comment by Avnsx** [comment]
Just checked, yes it would be possible. Would you prefer them to be epoch time stamps or converted to human time? I think windows only sorts them correctly in folders if they've some sort of numeric order. so the only way to achieve a good sorting, is when they stay epoch time stamps. You can look at what a epoch time stamp is here: https://www.epochconverter.com/

**Comment by pamman2** [comment]
I think I would like it to be converted to human time, but having both added can be useful for others that prefer epoch time. Currently I use YYYY-MM-DD as the human time format

**Comment by e2489** [comment]
Yeah, this would be very useful. Or an option to keep the original filenames (the way OF DataScraper does), as they're in order already. The issue currently is this scrapes from newest to oldest, so there's like 10 files labeled as "01", for each time we run an update.

**Comment by Avnsx** [comment]
Added in [version v0.3.4](https://github.com/Avnsx/fansly/releases/tag/v0.3.4)
The function is accessible using the setting ``naming_convention`` with value ``Datepost`` in config.ini

Read more about it here: https://github.com/Avnsx/fansly/wiki/Explanation-of-provided-programs-&-their-functionality#4-configini

You can use the updater, to comfortably upgrade to the new version.
