### ISSUE TITLE
Name files based on post text content?

### ISSUE THREAD

**Issue by ttrv65ebyng** [Avnsx/fansly#29]
Hi! I was wondering if it would be possible to scrape the text posted alongside media on a post and name the files accordingly? Something like [POST_TEXT]-1 ([FILENAME]).[EXT],  [POST_TEXT]-2 ([FILENAME]).[EXT] for 2 pieces of media attached to the same post? Either way, really appreciate the project! Thank you!

**Comment by Avnsx** [comment]
Yes most likely possible, but not interested in adding this
