### ISSUE TITLE
API returned unauthorized

### ISSUE THREAD

**Issue by sashacorosk** [Avnsx/fansly#30]
Hey,
firstly thank you for this, it's really a nice tool to use !
I used it several times without issues. I didnt change anything but now I have this message : [11]ERROR | 20:56 || API returned unauthorized. This is most likely because of a wrong authorization token, in the configuration file.

But I cant change the authorization token.

Can you tell me what to do there ? Thank you very much !

**Comment by Avnsx** [comment]
> But I cant change the authorization token.

The authorization token is bound to the credentials of your fansly account. If you for example turned on two factor authentication (2FA) recently or changed your accounts password; that means that the old authorization token you had fetched before with [Quick Start](https://github.com/Avnsx/fansly#-quick-start) is now invalid and you'll have to do Quick Start again to get the new authorization token for your account.

**Comment by sashacorosk** [comment]
Yeah I started again "Automatic Configurator" file. But I still have the same issue.
The only thing I did to explain why it doesnt work anymore is that I loggued out. But I dont even have a password on fansly, i'm logging in with Google. And I didnt change a thing about this. I'm clueless

**Comment by Avnsx** [comment]
@sashacorosk delete the config.ini file first and then start automatic configurator, once it's done try scraping with fansly scraper.

If that doesn't work delete config.ini again, [get the authentication token manually ](https://github.com/Avnsx/fansly/wiki/Get-Started) and add it into config.ini and try like that

**Comment by sashacorosk** [comment]
it's not giving me a new token. Still the same after reseting the config file. I still have the same error message.
I'll try manually but I checked it earlier and I couldnt manage to do it

**Comment by Avnsx** [comment]
> it's not giving me a new token.

My bad I just double checked with fansly api, it seems like they've removed the authentication token from the apiv2 requests. They're mainly using api verison 3 now and the authentication token is only inside the api version 3 requests.  You've to type in apiv3 to find the authentication token now.

I expected this to happen, you can read about it here: https://github.com/Avnsx/fansly/issues/23

**Comment by sashacorosk** [comment]
Yeah I read that too. So I tried with "apiv3" but I cant find anything with this search. Am I doing it wrong or it's normal till you fix it ?

**Comment by sashacorosk** [comment]
But I am not sure to understand step 3.. I dont see how I have to "locate a request"

**Comment by Avnsx** [comment]
> But I am not sure to understand step 3.. I dont see how I have to "locate a request"

When you type in "apiv3" where it asks you to in step 2, there'll only be a couple entries in the "names" field. One of them will be account?ids for example and you're supposed to find that one and look into the part where it says request headers for that request. In there you'll find the authorization token, once you copy it and paste it into the config.ini file together with your User-Agent which you can also find in that same file, fansly scraper will work again.

But if you don't understand how to do this, you'll have to wait for me to publish the next update. Which might be later today or tommorow

**Comment by sashacorosk** [comment]
It's ok, I find out ! it's because it wasnt looking the same to me than in the screenshot. It's working now ! thank you very much !

**Comment by Avnsx** [comment]
Fixed in https://github.com/Avnsx/fansly/releases/tag/v0.3.4
You can use the updater, to comfortably upgrade to the new version.
