### ISSUE TITLE
Can's download accounts with emojis in their name

### ISSUE THREAD

**Issue by Trasma** [Avnsx/fansly#31]
As the title suggests, it gives me the error where you misspelled their name, but i did not, I think its is due to the emojis in their name

**Comment by Avnsx** [comment]
I didn't even know you could use emojis in your accounts names. Are you sure this is an ongoing issue?

**Comment by Trasma** [comment]
> 

I was able to figure in out. Take this name for example, 👑👾Luna Queen👾👑, if you put that in it fails, but if you put in, LunaQueen, it works. I have another downloader and it listed all the names so i could see them before selecting someone to scrape

**Comment by Trasma** [comment]
i tired with one other emoji named person, and it also failed

**Comment by Avnsx** [comment]
Because those are not the actual usernames, that's their custom set site names... You've to put in what it says after the @CreatorUsername  or what it says in the url bar of the creator after the /

**Comment by Trasma** [comment]
okay, my mistake
