### ISSUE TITLE
API Returned unauthorized

### ISSUE THREAD

**Issue by ForcedToRock** [Avnsx/fansly#39]
This started happening after updating to 0.3.4. The error message would show "Used authorization token" but it's completely different from the actual cookie. Pretty much like this issue.
https://github.com/Avnsx/fansly/issues/30

**Comment by Avnsx** [comment]
1. What browser and Operating System are you using?
2. Does your fansly account have two factor authentication enabled?
4. Have you just recently tried getting the auth token with Automatic Configurator?
5. If you have tried getting it with Automatic Configurator does your auth token string end with ``fNs``?
6. Does the issue also happen when you manually add the auth token with the Get Started Tutorial?

**Comment by ForcedToRock** [comment]
1. Firefox, Windows 10
2. No
3. Yes, it spits out some cookie that starts with "M4" but when I got the cookie manually, it's something else.
4. Yes
5. Yes
6. It happens on both occasions, after using the automatic configurator, and then after manually adding the token.

**Comment by Avnsx** [comment]
Okay I figured out why this happens will push a fix soon, also I developed the recent update over a little time span and I forgot I did not properly finished implementing stuff that I thought I had implemented properly, which resulted in all these issues

**Comment by Avnsx** [comment]
@forcedtorock one more question, was automatic configurator even able to get the correct token from firefox in version 0.3.3 (the version before)? I am wondering if I should improve automatic configurators support for firefox or if it was getting the job done already good before

**Comment by ForcedToRock** [comment]
No, it spit out a token that ends in ZGE, while manually getting the token reveals one that ends in something different. I couldn't run the scraper fully anyway because it keeps prompting for an update, even though 0.3.4 got removed. I would try to "update" but the scraper would close by itself afterward.

**Comment by Avnsx** [comment]
Have you tried out automatic configurator on version 0.3.5 now? I just recently released it as executable @ForcedToRock

**Comment by ForcedToRock** [comment]
It didn't get the right token.
