### ISSUE TITLE
Can't get past trying to update

### ISSUE THREAD

**Issue by codyhood321** [Avnsx/fansly#42]
![image](https://user-images.githubusercontent.com/11204526/187558984-9a11971d-4d9b-42a0-aa50-b2865dff8ac9.png)

**Comment by Avnsx** [comment]
I removed that version, old one should work now. will release newer 0.3.5 version tomorrow

**Comment by Avnsx** [comment]
Fixed entirely, you should be able to update to 0.3.5 now.

Or manually download here: https://github.com/Avnsx/fansly/releases/tag/v0.3.5
