### ISSUE TITLE
Cannot download media from messages

### ISSUE THREAD

**Issue by Ghigi96** [Avnsx/fansly#47]
i always get "No scrapeable media found in mesages" but the timeline posts are downloading, is it still to be implemented or it's a bug related to my configuration? i used the automatic config, and i'm using the exe ones (0.3.5)

**Comment by Avnsx** [comment]
Are you sure fansly scraper is logged into the correct account, which has access to the correct message history that you are trying to scrape?

I just tried with a random creator, worked well for me; not bugged out or anything

Otherways just name the creator that you are encountering this bug with
