### ISSUE TITLE
Did I miss a step

### ISSUE THREAD

**Issue by EricVodka** [Avnsx/fansly#48]
I used the auto config.
Entered the name I wanted.
Ran the scraper, the scraper couldn't find the folder where to download. It didn't create one so I did using the exact name and interior folder names. It ran saying it was downloading a bunch of files, but once fully finished only videos were downloaded. 

I double checked the folder names and they are exactly like the prompt.  At first I thought I was due to the folder, but since the videos are downloading I am very confused why the photos are not.

**Comment by EricVodka** [comment]
![mgf](https://user-images.githubusercontent.com/113214985/189452727-0a5be906-05d3-4306-b98d-d3a2adeb6520.jpg)

**Comment by Avnsx** [comment]
Why did you cut out the part at the bottom where it says the location it saved the content at?

**Comment by EricVodka** [comment]
Saved in directory: "C:\Users\EricVodka\Desktop\Fansly_Scraper\TyGard_Photos_fansly"

**Comment by Avnsx** [comment]
Then why don't you look in there? If there's nothing inside, then right click the folder and make sure it's allowed to write in there by setting permissions

**Comment by EricVodka** [comment]
Okay I figured it out. The folder needed to be named Pictures... not Photos. Its working now.

**Comment by Avnsx** [comment]
Why would you ever rename it in first place
