### ISSUE TITLE
Error 4

### ISSUE THREAD

**Issue by LostPriest** [Avnsx/fansly#5]
It says my configuration file is malformed but everything is correct

**Comment by Avnsx** [comment]
> It says my configuration file is malformed but everything is correct

I did not do a good job at catching that exception, that printed you this. I just edited the code with comnmit 609e55194ba6b1e17971708f56cfb3418854460f, just download the raw source and run it with python and see if the new exception output helps you. If you need further help copy paste me the output here. After you've verified that your auth token is correct, make sure you remove the line that prints it in the error output. Please also name your creator, after you've verified that the output is not pointing to a end user mistake.

**Comment by LostPriest** [comment]
I do apologize as I found what I believe to be the problem, it seems it was my fault.

**Comment by Avnsx** [comment]
> I do apologize as I found what I believe to be the problem, it seems it was my fault.

No problem, I would be happy about a favorite on the repo 👍
