### ISSUE TITLE
Getting this error on macos

### ISSUE THREAD

**Issue by buangsaja** [Avnsx/fansly#55]
output(2,'\n [2]ERROR','<red>', f'"{e}" is missing or malformed in the configuration file!\n{21*" "}Read the Wiki > Explanation of provided programs & their functionality > config.ini')
                                                                                                                                                                                           ^
SyntaxError: invalid syntax

This isn't an issue with running on macos vs Windows is it?

**Comment by Avnsx** [comment]
You edited your local version my code and broke it, is what that means

**Comment by samja666** [comment]
I am having the exact same issue. And i am sure i have not modified any of your code except the config.ini
