### ISSUE TITLE
Executable randomly closes; due to being Rate Limited

### ISSUE THREAD

**Issue by RobertoJKN** [Avnsx/fansly#56]
I leave it running in the background and after some downloads it simply closes (it's far from having downloaded everything). I'm using Windows 11 and set it to run as admin (without admin it also would close after a bit)

**Comment by RobertoJKN** [comment]
Managed to screenshot the error before it closed the program.
![PotPlayerMini64_twQkAnZmHr](https://user-images.githubusercontent.com/32022277/205464626-1226bdfb-c830-42d1-b0bd-b48dd01eff20.png)

**Comment by Avnsx** [comment]
You're being rate limited by the fansly API. After a dozen of requests they eventually just forcefully close the connection.

Most likely that rate limit was newly introduced, might've to update fansly scraper to counter that soon.

Maybe try using a VPN and see if that helps

**Comment by RobertoJKN** [comment]
> You're being rate limited by the fansly API. After a dozen of requests they eventually just forcefully close the connection.
> 
> Most likely that rate limit was newly introduced, might've to update fansly scraper to counter that soon.
> 
> Maybe try using a VPN and see if that helps

Will try a VPN then, thanks for the quick response.

**Comment by Avnsx** [comment]
If that doesn't help you can also just continue the download from the point it shutdowned at, by setting ``update_recent_download`` to True

https://github.com/Avnsx/fansly/wiki/Explanation-of-provided-programs-&-their-functionality#4-configini

https://github.com/Avnsx/fansly/discussions/16

**Comment by RobertoJKN** [comment]
Using a VPN fixed it

**Comment by Avnsx** [comment]
Nice, guess we can call it a day here

Favorite the repo to support it

**Comment by Avnsx** [comment]
@RobertoJKN
Hey sorry to bother you one more time, but I have a question, how much internet download speed do you have?
And do you maybe know if you have a SSD or HDD drive?

**Comment by Avnsx** [comment]
@RobertoJKN
Hey sorry to bother you one more time, but I have a question, how much internet download speed do you have?
You can test it here: https://www.speedtest.net/

And do you maybe know if you have a SSD or HDD drive?

Also is this happening for you, everytime you're not using the VPN?

Would you mind helping me debugging fansly scraper and possibly fix this rate limiting issue, based on your feedback?

**Comment by Avnsx** [comment]
Most likely fixed in https://github.com/Avnsx/fansly/commit/b30a65df220f13b95cba5fa4e5b032baa82a1d75
