### ISSUE TITLE
Getting Error When Running

### ISSUE THREAD

**Issue by BDM96** [Avnsx/fansly#6]
When I run the scraper I get the error " "'TargetedCreator'" is missing or malformed in the configuration file! Read the ReadMe file for assistance." 

I copied the authorization and User-Agent from the dev tools as explained in the ReadMe but I still get the error. Should they be in quotes or a space between the = and the information I am putting into the config file?

**Comment by Avnsx** [comment]
> When I run the scraper I get the error " "'TargetedCreator'" is missing or malformed in the configuration file! Read the ReadMe file for assistance."
> 
> I copied the authorization and User-Agent from the dev tools as explained in the ReadMe but I still get the error. Should they be in quotes or a space between the = and the information I am putting into the config file?

No spaces, just read step 7.

**Comment by BDM96** [comment]
For step 7 I'm putting the username of the user pulled from the page and making sure it matches the username in the URL but still receive the same error. For example it is Username=lillieadd

**Comment by Avnsx** [comment]
> For step 7 I'm putting the username of the user pulled from the page and making sure it matches the username in the URL but still receive the same error. For example it is Username=lillieadd

Make sure there's no invisible characters and that you've really only replaced the ``ReplaceMe``'s with your data. The = and so on has to stay there. The error is clearly pointing at you not managing to properly write the config file in the required format. 
Here's the original file for reference https://github.com/Avnsx/fansly/blob/main/config.ini
It has to be in the same file directory as the .exe or .py file you launched the code with.

**Comment by Avnsx** [comment]
> When I run the scraper I get the error " "'TargetedCreator'" is missing or malformed in the configuration file! Read the ReadMe file for assistance."
> 
> I copied the authorization and User-Agent from the dev tools as explained in the ReadMe but I still get the error. Should they be in quotes or a space between the = and the information I am putting into the config file?

I just reproduced this; for this to happen you must have edited ``[TargetedCreator]`` away from the first line, or edited / removed it in general.  Your first two lines would need to look like this 

```python
[TargetedCreator]
Username=lillieadd
```
