### ISSUE TITLE
Scraper detect creator pictures but does not download anything

### ISSUE THREAD

**Issue by MudRotr** [Avnsx/fansly#63]
I do a manual setup and run the scraper, the scraper runs smoothly and detects some pictures but does not download anything from the creator 
![Screenshot 2023-01-13 020040](https://user-images.githubusercontent.com/122563027/212157755-d3309944-bddf-420e-90af-d026f1e5a2bc.png)

**Comment by Avnsx** [comment]
You prolly linked the authentication of a alt / new account you just made to use fansly scraper with and this is the result of that
