### ISSUE TITLE
(13) ERROR ?

### ISSUE THREAD

**Issue by Grosman69** [Avnsx/fansly#64]
Doesn't work
![slika](https://user-images.githubusercontent.com/123072138/213417815-8d0161b1-8dcf-40d1-b4da-4b30c9dac8c1.png)

 Info | 11:23 || Reading config.ini file ...

 [13]ERROR | 11:23 || API returned unauthorized. This is most likely because of a wrong authorization token, in the configuration file.
                     Used authorization token: "Mzk5MjA0OTc5NjE0Njg3MjMyOjE6MTozNTRlNDI3N2Y5YjEzM2QxODQwZTc4N2Y5OGUwMzI"
'response'
{"success":false,"error":{"code":401,"details":"unauthorized"}}

Press any key to close ...

**Comment by Avnsx** [comment]
Judging by the character length & form of that auth token, I can already tell that it's not a valid auth token and don't really know where you got this one from. 

Try to just re-start automatic configurator and hope it'll get you a correct token else follow [this tutorial](https://github.com/Avnsx/fansly/wiki/Get-Started) and get the correct auth token.
