### ISSUE TITLE
All images are in PNG

### ISSUE THREAD

**Issue by kervala** [Avnsx/fansly#66]
Hi,

Thanks a lot for this software, it works fine :)

When I scrape any creator, I only get PNG images while when I check with Chrome developer tools, I can see most of them are in JPEG. Please is that the expected behavior ? Are they converted ?

Thanks :)

**Comment by Avnsx** [comment]
Fanslys website renders most images in jpeg only to keep the site more responsive and smoother to load with older/mobile hardware. Most images are not ever loaded in their highest resolution that they were stored in, unless you're forcefully get them from the API. 
Fansly scraper is exactly doing this, it's taking the highest resolution pictures possible, which in this case means no jpegs unless the jpeg is truly the highest resolution, which was stored by their internal API.

```
Is PNG more detailed than JPEG?

The biggest advantage of PNG over JPEG is that the compression is lossless, meaning there is no loss
in quality each time it is opened and saved again. PNGs are often used if size is not an issue and the image
is complex, because a PNG file holds more information than a JPG.
```

**Comment by Avnsx** [comment]
> So there is no way to get the original images artists uploaded on Fansly ?

No, you can't view the original quality of images on the Fansly website itsself.

As of right now you can only use Fansly Scraper, to get the original (highest) quality media and view it on your local machine instead.

**Comment by kervala** [comment]
Hehe, so we're lucky to be able to get the PNG files, since they are not used by their scripts and not displayed to users :)
