### ISSUE TITLE
API unauthorized issues

### ISSUE THREAD

**Issue by devicemodder** [Avnsx/fansly#67]
Hello, i followed your instructions to the letter, and i get:

 [13]ERROR | 22:25 || API returned unauthorized. This is most likely because of a wrong authorization token, in the configuration file.

when trying to run the downloader

**Comment by Avnsx** [comment]
Try using automatic configurator or re-start following the instructions again, there's not really a way for me to help you with this

**Comment by devicemodder** [comment]
Got it working
