### ISSUE TITLE
Wrong Authorization token

### ISSUE THREAD

**Issue by crimsondre3** [Avnsx/fansly#74]
I'm not sure if it's my account being new, but i've tried using the scraper but it keeps popping up Wrong authorization token. If it's my account being new or I am doing something wrong.

**Comment by Avnsx** [comment]
Yes you must be doing something wrong, it has nothing to do with your account being new.
Delete & get a fresh copy of config.ini and try using automatic configurator to get the auth token for you.

Else try the manual tutorials: https://github.com/Avnsx/fansly/wiki/Get-Started

**Comment by crimsondre3** [comment]
I have setted up but it keeps saying 0 images and 0 videos downloaded. I have a vpn and changed my DNS provided by cloudflare but it keeps popping up after it is done that no images were downloaded.
![2023-03-28 (4)](https://user-images.githubusercontent.com/129136386/228327513-75d240b5-ffb9-4de7-aa4b-d2ee240e1cda.png)

**Comment by Avnsx** [comment]
look at what it says at the very bottom below done

**Comment by crimsondre3** [comment]
I checked the folder and it is empty despite the scraper working

**Comment by Avnsx** [comment]
> I checked the folder and it is empty despite the scraper working

That's not the point, it's prolly saying something like follow the creator to scrape more or subscribe or something
