### ISSUE TITLE
New feature suggestion: scrape multiple users at once

### ISSUE THREAD

**Issue by RalkeyOfficial** [Avnsx/fansly#79]
Since this scrapper has automatic hash checker, I thought about using it to just automatically scrape all new content without having to actually open Fansly (so I can be extra lazy :))

But the only problem hindering me from being the laziest human imaginable is that I need to change the `username` in the `config.ini` every time.

So my suggestion is that the `username` field can take in an array of usernames,
which can then be looped through, and the rest of the code can be the same.

**Comment by Avnsx** [comment]
The codebase is currently written too entangled to introduce a feature like this, so I've to refuse this suggestion at this point in time.
